language: go

go:
  - "1.x"
  - "1.14"

script:
  -  make clean
  -  make
  -  make clean
  -  make build
  -  make clean
  -  make debugbuild
  -  make clean
  -  'if [ $TRAVIS_EVENT_TYPE != "pull_request" ]; then make updatedeps; fi'
  -  make citest
